// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxLQ0MGOrhf8Sw7Zi_QGokj5Wq56BCcU4',
    appId: '1:617292015522:web:316e44b4ebad462defb4fb',
    messagingSenderId: '617292015522',
    projectId: 'chron-sec',
    authDomain: 'chron-sec.firebaseapp.com',
    storageBucket: 'chron-sec.firebasestorage.app',
    measurementId: 'G-W64PN3LHSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgNFel_3wX-KUFLHGdmthVGlw4tRpe58g',
    appId: '1:617292015522:android:83303bfea655d26aefb4fb',
    messagingSenderId: '617292015522',
    projectId: 'chron-sec',
    storageBucket: 'chron-sec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_aaq7VJNGjcTSD7HMjbEC1ps5YjqKcDk',
    appId: '1:617292015522:ios:9381642a4c5acba2efb4fb',
    messagingSenderId: '617292015522',
    projectId: 'chron-sec',
    storageBucket: 'chron-sec.firebasestorage.app',
    iosBundleId: 'com.example.crohn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_aaq7VJNGjcTSD7HMjbEC1ps5YjqKcDk',
    appId: '1:617292015522:ios:9381642a4c5acba2efb4fb',
    messagingSenderId: '617292015522',
    projectId: 'chron-sec',
    storageBucket: 'chron-sec.firebasestorage.app',
    iosBundleId: 'com.example.crohn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxLQ0MGOrhf8Sw7Zi_QGokj5Wq56BCcU4',
    appId: '1:617292015522:web:dbdc5fc094ef018fefb4fb',
    messagingSenderId: '617292015522',
    projectId: 'chron-sec',
    authDomain: 'chron-sec.firebaseapp.com',
    storageBucket: 'chron-sec.firebasestorage.app',
    measurementId: 'G-8E7KW4EQQJ',
  );
}
